// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import './globals.css'
//
// const inter = Inter({ subsets: ['latin'] })
//
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
//
// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }
//
export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <div className="flex hscreen flex-col md:flex-row md:overflow-hidden">
            <div className="w-full flex-none md:w-64">
                <h1>I love you Theila!</h1>
            </div>
            <div className="flex-grow p-6 md:overflow-y-auto md:p-12"></div>
        </div>
    );
}